### ISSUE TITLE
'zap' doesn't unmount all mounts

### ISSUE THREAD

**Issue by craftyguy** [postmarketOS/pmbootstrap#263]
After rebasing off of the master branch here, `pmbootstrap zap` doesn't unmount all mounts, resulting in a failure:

```
$ ./pmbootstrap.py zap                                                                                                               i 
[21:36:54] Unregister qemu binfmt (arm)              
[21:36:56] Shutdown complete                
[21:36:56] Remove /home/clayton/src/pmbootstrap-out/chroot_native? (y/n) [n]: y          
[21:37:04] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/clayton/src/pmbootstrap-out/log.txt                                                       
[21:37:04] ERROR: Command failed: % sudo rm -rf /home/clayton/src/pmbootstrap-out/chroot_native                                                                                    
[21:37:04] Run 'pmbootstrap log' for details.                                            
[21:37:04] See also: <https://postmarketos.org/troubleshooting>   
```

[Here is the full log file.](https://craftyguy.net/pub/pmbootstrap.log)

Here is output from `mount` after running `zap`:

```
$ mount
...
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/var/cache/apk type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/home/user/.ccache type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/var/cache/distfiles type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/home/user/git type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/home/user/.abuild type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/etc/apk/keys type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/home/user/packages/user type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
proc on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/proc type proc (rw,nosuid,nodev,noexec,relatime)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/var/cache/apk type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/.ccache type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/var/cache/distfiles type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/git type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/.abuild type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/etc/apk/keys type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/packages/user type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
devtmpfs on /media/data/clayton/src/pmbootstrap-out/chroot_native/dev/install type devtmpfs (rw,nosuid,size=16168212k,nr_inodes=4042053,mode=755)
devtmpfs on /media/data/clayton/src/pmbootstrap-out/chroot_native/dev/installp1 type devtmpfs (rw,nosuid,size=16168212k,nr_inodes=4042053,mode=755)
devtmpfs on /media/data/clayton/src/pmbootstrap-out/chroot_native/dev/installp2 type devtmpfs (rw,nosuid,size=16168212k,nr_inodes=4042053,mode=755)
/dev/installp2 on /media/data/clayton/src/pmbootstrap-out/chroot_native/mnt/install type ext4 (ro,relatime,data=ordered)
/dev/installp1 on /media/data/clayton/src/pmbootstrap-out/chroot_native/mnt/install/boot type ext2 (rw,relatime,block_validity,barrier,user_xattr,acl)
/dev/mapper/data on /media/data/clayton/src/pmbootstrap-out/chroot_native/mnt/rootfs_nokia-rx51 type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
```

**Comment by craftyguy** [comment]
@ollieparanoid, fyi since this is very reproducible for me with a 'new install' of PMOS.

**Comment by ollieparanoid** [comment]
Thanks for reporting.
* Does this also happen, when your work folder is *not* a symlink? (#149)
* Which commit was the last one, that worked for you?
* Could you verify, that it still works if you check out that commit?

**Comment by craftyguy** [comment]
> Does this also happen, when your work folder is not a symlink? (#149)

Yes, even when it is not a symlink, I still get a bunch of "Device or resource busy" errors after "shutdown complete".

> Which commit was the last one, that worked for you?

Unfortunately I don't remember. I've been working in a few different branches working on various things, and about twice a day I will fetch from your repo and rebase to keep things current. I will try going through the recent changes to the 'zap' function (if any) to see if there's anything obvious.

**Comment by ollieparanoid** [comment]
Good strategy (although I think we didn't really change the zap function). You could also do a git bisect from a few days ago until now to find the troubling commit.

**Comment by craftyguy** [comment]
Ok I didn't see anything in zap.. it hasn't been changed for quite some time. My guess is the 'shutdown' isn't working properly.

I cloned your repo's master branch to a fresh directory, pointed it to a completely new and empty (non-symliked) work directory, ran 'install' (which completed successfully), then tried to zap it and still get the device/resource busy error. Here's the full log from that experiment: https://craftyguy.net/pub/log2.txt

**Comment by craftyguy** [comment]
Actually, on careful inspection of the log, it looks like `/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user` isn't even unmounted in the previous 'shutdown' sequence. I don't see it listed there.

**Comment by ollieparanoid** [comment]
Great find! The umount code is in `pmb/helpers/mount.py:umount_all()`.
Could you debug that a bit? What does your `/proc/mounts` look like, does it match with what `mount` says?
What happens, if you try to manually umount the entries, just like the script would do?

**Comment by craftyguy** [comment]
> What does your /proc/mounts look like, does it match with what mount says?

Yes:

```
$ grep pm-out /proc/mounts                                                                                                                                                        
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
$ mount |grep pm-out
/dev/mapper/data on /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
```

> What happens, if you try to manually umount the entries, just like the script would do?

It umounts just fine if I manually do it. In fact, I call a simple for loop to essentially umount everything matching in /proc/mount as a workaround for this issue.

I'll take a look at `umount_all()`

**Comment by ollieparanoid** [comment]
Your first log starts with:

```
(001358) [21:36:54] Unregister qemu binfmt (arm)
(001358) [21:36:54] % sudo sh -c echo -1 > /proc/sys/fs/binfmt_misc/qemu-arm
(001358) [21:36:56] Shutdown complete
[21:36:56] Remove /home/clayton/src/pmbootstrap-out/chroot_native? (y/n) [n] y
(001358) [21:36:58] % sudo rm -rf 
/home/clayton/src/pmbootstrap-out/chroot_native
```

... while your `/proc/mount` output has:
```
$ grep pm-out /proc/mounts                                                                                                                                                        
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
```
In conclusion, `/home/clayton/src/pmbootstrap-out/` is a symlink to `/media/data/clayton/src/pm-out/`.

I'm sorry, that pmbootstrap has quite a few bugs when having the `work` folder symlinked - not only in shutdown, but also in the timestamp based rebuilds and probably some other places where it compares paths. That will all be fixed in #271.

I guess I misread your previous statement:
> Yes, even when it is not a symlink, I still get a bunch of "Device or resource 
busy" errors after "shutdown complete".

This is a totally different issue (maybe the same as #166?). I did not realize, that because you had another error, you assumed, that changing the symlink didn't work and kept using it.

Anyway, **please use a path without any symlinks until #271 is resolved.** To make sure, that you're doing that, run `pmbootstrap init` again and type in `/media/data/clayton/src/pm-out/` as work folder.

Please report back if that workaround helps you with the issues, that you have. After that I suggest closing this issue, as it duplicates #271 now (which has less noise and is easier to read), and possibly #166.

Sorry for the inconvenience.

**Comment by craftyguy** [comment]
@ollieparanoid I've since moved away from accessing my work folder through a symlink, but I am still experiencing some very strange behavior:

1) If I comment out the `pmb.helpers.run.root(args, ["umount", words[1]])` (and comment out the check later on to raise error if ismount is true), and add a print that literally just prints out the `words[1]`, I can see all of the mounts in /proc/mounts that should be unmounted.

2) If I uncomment the call to `pmb.helpers.run.root` and leave the print in that just prints `words[1]`, I never see the very last mount printed (or unmounted), it remains in /proc/mounts after `umount_all` returns. It just so happens that most of the time the very last line in /proc/mounts is `/media/data/clayton/src/pmbootstrap-out/chroot_rootfs_nokia-rx51/home/user/packages/user`, but I have seen it be other paths too in my testing.

### *Commented out call to pmb.helpers.run.root*

Output from `zap`:
```
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/etc/apk/keys
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/packages/user
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/etc/apk/keys
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user
###################################
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/etc/apk/keys
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/packages/user
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/etc/apk/keys
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user
```

`grep /media/data/clayton/src/pm-out /proc/mounts`
```
proc /media/data/clayton/src/pm-out/chroot_native/proc proc rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/var/cache/apk ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/home/user/.ccache ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/var/cache/distfiles ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/home/user/git ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/home/user/.abuild ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/etc/apk/keys ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_native/home/user/packages/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
proc /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/proc proc rw,nosuid,nodev,noexec,relatime 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/apk ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.ccache ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/distfiles ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/git ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.abuild ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/etc/apk/keys ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
```

Edit to `pmb.helpers.mount`

```
  7         for line in handle:
  6             words = line.split()
  5             if len(words) < 2 or not words[1].startswith(folder):
  4                 continue
  3             print("UMOUNT :" + words[1])
  2             #ret = pmb.helpers.run.root(args, ["umount", words[1]])
  1             #if ismount(words[1]):
94                  #raise RuntimeError("Failed to umount: " + words[1])
```

### *pmb.helpers.run.root call is NOT commented out*

Output from `zap`:

```
###################################
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/etc/apk/keys
UMOUNT :/media/data/clayton/src/pm-out/chroot_native/home/user/packages/user
###################################
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/proc
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/apk
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.ccache
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/var/cache/distfiles
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/git
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/.abuild
UMOUNT :/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/etc/apk/keys
[08:48:20] Shutdown complete
```

`grep /media/data/clayton/src/pm-out /proc/mounts`:


```
/dev/mapper/data /media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user ext4 rw,relatime,discard,errors=remount-ro,data=ordered 0 0
```

Edits to pmb.helpers.mount:


```
  5         for line in handle:
  4             words = line.split()
  3             if len(words) < 2 or not words[1].startswith(folder):
  2                 continue
  1             print("UMOUNT :" + words[1])
92              ret = pmb.helpers.run.root(args, ["umount", words[1]])
  1             #if ismount(words[1]):
  2                 #raise RuntimeError("Failed to umount: " + words[1])
```

Here is my pmbootstrap.cfg for good measure:

```
[pmbootstrap]
alpine_version = edge
config = /home/clayton/.config/pmbootstrap.cfg
device = nokia-rx51
timestamp_based_rebuild = False
log = $WORK/log.txt
mirror_alpine = https://nl.alpinelinux.org/alpine/
mirror_postmarketos =
work = /media/data/clayton/src/pm-out
port_distccd = 33632
ui = weston
cipher = aes-cbc-plain64
jobs = 9
```


Notice how `/media/data/clayton/src/pm-out/chroot_rootfs_nokia-rx51/home/user/packages/user` never shows up in the second experiment where `umount` is actually called. It's almost like `umount_all` doesn't get a chance to process all of /proc/mounts... I have tried instrumenting the calls to `run.root`, `run.user`, and `run.core`, but no exceptions are thrown. It's like the very last mount in `/proc/mounts` just doesn't exist when `/proc/mounts` is being modified by calls to `umount` from within `umount_all`.

**Comment by ollieparanoid** [comment]
Thank you for this detailed response and further testing.
I will need to read to take some time to analyze this, and I will do that.

However, I am a bit unsure what the actual error is you are getting, since we are explicitly not looking at the symlink issue anymore.
If it is the order of the umounts, that is wrong, it should already be fixed in #274. Either way, please try this PR out, it refactors the `umount_all` function to make it more accessible in testcases.
You can run the test with `pytest test/test_mount.py`.

If that PR does not help you, please post the error message you're currently getting - along with a good chunk of the end of `pmbootstrap log`. Thanks!

**Comment by craftyguy** [comment]
I wasn't getting an error in my test above because I was stopping it before trying to delete chroots since there was one lingering mount. The 'error' would have been "unable to umount, device/resource busy".

In any case, I'm unable to reproduce this using the refactored code in #274. I'm still curious why I wasn't seeing any exceptions though.. it seems like a failed umount because of a nested mount or something would have raised an exception. *shrug*
